name: pkg.pr.new

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main

jobs:
  pkg-pr-new:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate exports
        run: bun run generate-exports

      - name: Build package
        run: bun run build --if-present

      - name: Publish to pkg.pr.new
        run: bun run pkg-pr-new
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
